/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nopzailinpqsrwposmvo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vcHphaWxpbnBxc3J3cG9zbXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNDM2NjksImV4cCI6MjA3NDcxOTY2OX0.Jum6snWrMovhk7Asn-XgzYbkh3Xi-DlmbOx6Z2G76pc"